# Generated by Django 5.2.6 on 2025-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('naturalidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='images/jogadores/')),
            ],
        ),
    ]
